New Connector Sdk example
fivetran/fivetran_connector_sdk pull request #33
Opened 2024-09-22 13:42 UTC by fivetran-satvikpatil

Link https://fivetran.height.app/T-779297

### Description
Add example usage of a cursor to get the data

2024-09-24 08:25 UTC, fivetran-rishabhghosh requested changes
Please rebase. There is a change in the directory structure

2024-09-27 05:21 UTC, varundhall requested changes
please be consistent with all the methods comment, also reformat the file using Pycharm (Code->Reformat File)

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +
```suggestion


```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +def schema(configuration: dict):
```suggestion
# - configuration: a dictionary that holds the configuration settings for the connector.
def schema(configuration: dict):
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +def initialize_state(state):
```suggestion
def initialize_state(state: dict):
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +        if(temp_list):
```suggestion
        if temp_list:
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +        if(end_time-start_time > 1):
```suggestion
        if end_time - start_time > 1:
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +    return (state, insert)
```suggestion
    return state, insert
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +        api_response = api_result.json()
looks this api_response is being shadowed from outer scope

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +                        json.dumps(api_response))
is same api_response available here?

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +    while(True):
```suggestion
    while True:
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +            if(insert_ticker_price_records_temp):
```suggestion
            if insert_ticker_price_records_temp:
```

2024-09-27 05:21 UTC, varundhall commented on examples/marketstack/connector.py
> +        except:
should we use better exception handling here, something like

```
except rq.exceptions.RequestException as e:
            raise Exception(f"Request failed: {e}")
        except json.JSONDecodeError as e:
            raise Exception(f"Failed to parse JSON response: {e}")
        except KeyError as e:
            raise Exception(f"Missing expected key in response: {e}")
```

2024-09-30 10:34 UTC, fivetran-satvikpatil commented on examples/marketstack/connector.py
> +                        json.dumps(api_response))
Changed the exception message.

2024-09-30 10:34 UTC, fivetran-satvikpatil commented on examples/marketstack/connector.py
> +        api_response = api_result.json()
Changed the exception message.

2024-10-01 08:35 UTC, varundhall approved these changes

2024-10-01 08:35 UTC, varundhall commented on examples/Common patterns for connectors/pagination/marketstack/connector.py
> +        raise Exception(f"Request failed: {str(e)}")
nit: RuntimeError instead of Exception here and other places, as per sonar

2024-10-01 08:35 UTC, varundhall commented on examples/Common patterns for connectors/pagination/marketstack/connector.py
> +        api_response = api_result.json()
nit: Shadows name 'api_response' from outer scope

2024-10-01 12:57 UTC, fivetran-rishabhghosh commented on examples/Common patterns for connectors/pagination/marketstack/requirements.txt
This empty file is not required

2024-10-01 12:58 UTC, fivetran-rishabhghosh commented on examples/Common patterns for connectors/pagination/marketstack/connector.py
> +if __name__ == "__main__":
Pass configuration.json to debug function so that anyone debugging via IDE would get the confugurations

2024-10-01 13:13 UTC, fivetran-rishabhghosh requested changes
Please address the comments

2024-10-03 07:16 UTC, fivetran-rishabhghosh approved these changes

2024-10-03 09:40 UTC, varundhall approved these changes
Please merge this at correct time as per the docs change PR, customers should not land up with HTTP 404 from our website.

2024-10-03 16:22 UTC, merged