fix(User Profiles Example): Handle NaN value from dataframes
fivetran/fivetran_connector_sdk pull request #44
Opened 2024-10-20 19:18 UTC by fivetran-satvikpatil

T-802267

### Changes
Provide example usage to remove the NaN value from the data frame before upserting.

2024-10-22 07:08 UTC, varundhall requested changes

2024-10-22 07:08 UTC, varundhall commented on examples/quick_start_examples/user_profiles/connector.py
> +import numpy as np
please add in requirements

2024-10-22 07:08 UTC, varundhall commented on examples/quick_start_examples/user_profiles/connector.py
> +    table_df_1 = table_df_1.replace(np.nan, None)
I think we should create a method and add proper comments like
Approach 1:
Approach 2:
etc

2024-10-23 09:36 UTC, varundhall approved these changes

2024-10-23 21:03 UTC, fivetran-sadiemartin commented on examples/quickstart_examples/user_profiles/connector.py
> +    # Approaches to handle NaN values in dataframes
Let's explain why NaN presents a problem here.

2024-10-23 21:03 UTC, fivetran-sadiemartin requested changes
Could we add to the comment at the top that this example shows how to work with data frames and how to handle NaN in data frames?

I didn't run the example - I'm assuming someone on engineering did to make sure that it still works?

2024-10-29 13:36 UTC, merged